{% set name = "pytest-celery" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1e431e408116c74b4e9f6803ec95dcda3e104ec59adfc2807f3c89fde3429337

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python
  run:
    - pytest

test:
  imports:
    - pytest_celery
  commands:
    - pip check
    - "pytest --fixtures | grep 'plugins: celery'"
  requires:
    - pip
    - celery >=4.4.0

about:
  home: https://github.com/graingert/pytest-celery
  summary: pytest-celery a shim pytest plugin to enable celery.contrib.pytest
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - igortg
