{% set name = "pytest-celery" %}
{% set version = "1.2.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_celery-{{ version }}.tar.gz
  sha256: de605eca1b0134c136910c8ed161cc3996b0c8aaafd29170878a396eed81b5b1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - poetry-core >=1.8.1
    - python {{ python_min }}
  run:
    - celery >=4.4.0
    - debugpy >=1.8.12,<2.0.0
    - docker-py >=7.1.0,<8.0.0
    - kombu
    - psutil >=7.0.0
    - pytest
    - pytest-docker-tools >=3.1.3
    - python >={{ python_min }},<4.0
    - setuptools >=75.8.0
    - tenacity >=9.0.0
  run_constrained:
    - boto3 *
    - botocore *
    - python-memcached *
    - redis-py *
    - urllib3 >=1.26.16,<2.0

test:
  imports:
    - pytest_celery
  commands:
    - pip check
    - "pytest --fixtures | grep 'plugins:.* celery'"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/celery/pytest-celery
  summary: Pytest plugin for Celery
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - igortg
