{% set name = "pytest-celery" %}
{% set version = "0.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-celery-{{ version }}.tar.gz
  sha256: cfd060fc32676afa1e4f51b2938f903f7f75d952186b8c6cf631628c4088f406

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python
  run:
    - pytest

test:
  imports:
    - pytest_celery
  commands:
    - pip check
    - "pytest --fixtures | grep 'plugins: celery'"
  requires:
    - pip
    - celery >=4.4.0

about:
  home: https://github.com/graingert/pytest-celery
  summary: pytest-celery a shim pytest plugin to enable celery.contrib.pytest
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - igortg
